services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - pg
    network_mode: host
  pg:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
volumes:
  pgdata:
